# Generated by Django 4.2.4 on 2023-08-15 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
