# Generated by Django 4.2.4 on 2023-08-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_category_slug_post_slug_tag_slug_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
