# Generated by Django 4.2.4 on 2023-08-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0003_remove_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
