# Generated by Django 4.2.4 on 2023-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0003_remove_post_comment_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default=1, upload_to='\\media\\profile_pics'),
            preserve_default=False,
        ),
    ]
