# Generated by Django 4.2.4 on 2023-08-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0005_comment_post_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
