# Generated by Django 4.2.4 on 2023-08-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0007_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
