# Generated by Django 4.2.4 on 2023-08-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0009_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('Post', models.ManyToManyField(related_name='tags', to='blogg.post')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-slug'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='Tag',
            field=models.ManyToManyField(blank=True, null=True, to='blogg.tag'),
        ),
    ]
