# Generated by Django 4.2.4 on 2023-08-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
