# Generated by Django 4.2.4 on 2023-08-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='slug',
        ),
    ]
